# Generated by Django 4.1.3 on 2023-11-06 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviceRequest', '0002_alter_servicerequest_executor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='request_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='serviceRequest.requeststatus', verbose_name='Status'),
        ),
    ]
