# Generated by Django 4.1.3 on 2023-11-08 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('serviceRequest', '0006_requeststatus_status_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequestChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField(verbose_name='Message')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceRequest.servicerequest', verbose_name='Service request')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ('id',),
            },
        ),
    ]
