# Generated by Django 4.1.3 on 2023-11-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceRequest', '0007_servicerequestchatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequestchatmessage',
            name='isRead',
            field=models.BooleanField(default=False, verbose_name='Is read'),
        ),
    ]
