# Generated by Django 4.1.3 on 2023-11-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceRequest', '0010_servicerequestchatmessage_date_time_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicerequest',
            options={'ordering': ('-id',), 'verbose_name': 'Request', 'verbose_name_plural': 'Requests'},
        ),
        migrations.AddField(
            model_name='requeststatus',
            name='isBlockChat',
            field=models.BooleanField(default=False, verbose_name='Is blocking chat'),
        ),
    ]
