# Generated by Django 4.1.3 on 2023-11-14 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceRequest', '0011_alter_servicerequest_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requeststatus',
            old_name='isBlockChat',
            new_name='is_block_chat',
        ),
    ]
