# Generated by Django 4.1.3 on 2023-11-15 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('serviceRequest', '0013_remove_servicerequestchatmessage_is_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_read', models.DateTimeField(auto_now_add=True, verbose_name='Date anf time of reading')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceRequest.servicerequestchatmessage', verbose_name='Message')),
                ('who_read', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Who read')),
            ],
            options={
                'verbose_name': 'Message_Reading',
                'verbose_name_plural': 'Message_Readings',
                'ordering': ('id',),
            },
        ),
    ]
